### ISSUE TITLE
Tests failing with 'ERROR: relation "project" does not exist'

### ISSUE THREAD

**Issue by shellac** [ox-it/ords-database-api#2]
I'm trying to get ORDS working using vagrant. (See https://github.com/ilrt/ords-vagrant)

I get two failures due to 'relation "project" does not exist', which suggests the database needs to be prepped in advance.

Surefire report https://gist.github.com/shellac/cfaa511ab780795e2f0d (since github doesn't recognise xml for issues).

[uk.ac.ox.it.ords.api.database.resources.DatabaseTest.txt](https://github.com/ox-it/ords-database-api/files/167176/uk.ac.ox.it.ords.api.database.resources.DatabaseTest.txt)

**Comment by krispopat** [comment]
I've removed the reference to the project table from the abstract test in both this and the database structure api.  Please test again to see if it works.

Many thanks
